### ISSUE TITLE
Fails with certain 6RD prefix mask values

### ISSUE THREAD

**Issue by piru** [daenney/sixrd#4]
The current code fails to calculate & pass the relay prefix argument. This leads to errors with certain 6rd options:
`sixrd: error: failed to execute: ip tunnel 6rd dev ipv6rd 6rd-prefix 2001:2003:fb80::/42: exit status 1`

Some options will work, but 2001:2003:fb80::/42 definitely does not. Pr #3 fixes this issue by calculating the correct value for 6rd-relay_prefix option and passing it to `ip tunnel` command.

With the fix I get command `ip tunnel 6rd dev 6rdif 6rd-prefix 2001:2003:fb80::/42 6rd-relay_prefix 86.115.0.0/18` which works correctly.

**Comment by daenney** [comment]
Fixed with #3
